name: Secret Scanning

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  secret-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      pull-requests: write # For commenting on PRs

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check for Globomantics Robot Tokens
        run: |
          echo "🔍 Checking for Globomantics robot tokens..."
          if grep -r -P "gbot-(dev|prod)-[A-Fa-f0-9]{16}" --exclude-dir={.git,.github} .; then
            echo "::error::Found potential Globomantics robot token!"
            exit 1
          fi

      - name: Check for AWS Keys
        run: |
          echo "🔍 Checking for AWS access keys..."
          if grep -r -P "AKIA[0-9A-Z]{16}" --exclude-dir={.git,.github} .; then
            echo "::error::Found potential AWS access key!"
            exit 1
          fi

      - name: Validate Token Format
        run: |
          echo "✨ Validating token formats..."
          # Read the pattern from our format definition
          pattern=$(grep -oP '^gbot-\(dev\|prod\)-\[A-Fa-f0-9\]\{16\}$' globomantics-robot-auth-token-formats.md || echo "")
          if [ -z "$pattern" ]; then
            echo "::warning::Token format definition not found or invalid"
          else
            echo "✅ Token format is valid"
          fi

      - name: Comment on PR
        if: github.event_name == 'pull_request' && failure()
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.name,
              body: '⚠️ Secret scanning found potential secrets in this PR. Please review and remove any exposed tokens.'
            }) 