name: Test Globomantics Secret Scanning Pattern

on:
  workflow_dispatch:

jobs:
  test-secret-pattern:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config user.name "Tim Warner"
          git config user.email "timothywarner316@gmail.com"

      - name: Create test branch
        run: |
          git checkout -b test-globomantics-secret-pattern

      - name: Add test secret
        run: |
          echo "firmware_token: gbot-dev-1234abcd5678ef90" >> test-secret.txt
          git add test-secret.txt
          git commit -m "Add test secret for scanning pattern"

      - name: Push test branch
        run: |
          git push origin test-globomantics-secret-pattern
