name: Test Secret Scanning Alert

on:
  workflow_dispatch:

jobs:
  test-secret-alert:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"

      - name: Create test branch
        run: |
          BRANCH_NAME="test-secret-alert-$(date +%s)"
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
          git checkout -b $BRANCH_NAME

      - name: Add test secret
        run: |
          echo "firmware_token: gbot-dev-1234abcd5678ef90" >> test-secret.txt
          git add test-secret.txt
          git commit -m "test: add sample Globomantics robot token for alert testing"

      - name: Push test branch
        run: |
          git push origin $BRANCH_NAME

      - name: Create PR
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr create \
            --title "test: verify secret scanning alert" \
            --body "This PR was automatically created to test the Globomantics robot token secret scanning pattern. An alert should be generated for the test token." \
            --base main \
            --head $BRANCH_NAME

      - name: Cleanup
        if: always()
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          git checkout main
          git push origin --delete $BRANCH_NAME || true 