name: Test Globomantics Secret Pattern

on:
  workflow_dispatch:
  push:
    paths:
      - 'globomantics-robot-auth-token-formats.md'
      - '.github/workflows/test-globo-secret-pattern.yml'

jobs:
  test-pattern:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Validate pattern format
        run: |
          pattern=$(grep -oP '^gbot-\(dev\|prod\)-\[A-Fa-f0-9\]\{16\}$' globomantics-robot-auth-token-formats.md || echo "")
          if [ -z "$pattern" ]; then
            echo "❌ Pattern validation failed"
            exit 1
          fi
          echo "✅ Pattern validation passed"

      - name: Test sample tokens
        run: |
          # Test valid tokens
          echo "Testing valid tokens..."
          echo "gbot-dev-0123456789abcdef" | grep -P "$(cat globomantics-robot-auth-token-formats.md | head -n 3 | tail -n 1)" && echo "✅ Valid dev token matched"
          echo "gbot-prod-fedcba9876543210" | grep -P "$(cat globomantics-robot-auth-token-formats.md | head -n 3 | tail -n 1)" && echo "✅ Valid prod token matched"
          
          # Test invalid tokens
          echo "Testing invalid tokens..."
          ! echo "gbot-stage-0123456789abcdef" | grep -P "$(cat globomantics-robot-auth-token-formats.md | head -n 3 | tail -n 1)" && echo "✅ Invalid environment rejected"
          ! echo "gbot-dev-0123456789abcde" | grep -P "$(cat globomantics-robot-auth-token-formats.md | head -n 3 | tail -n 1)" && echo "✅ Short token rejected"
          ! echo "gbot-prod-0123456789abcdefg" | grep -P "$(cat globomantics-robot-auth-token-formats.md | head -n 3 | tail -n 1)" && echo "✅ Long token rejected"
